# Generated by Django 5.2.4 on 2026-02-11 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('milestones', '0001_initial'),
        ('sales_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='sales_orders.salesorder'),
        ),
    ]
