# Generated by Django 5.2.4 on 2026-01-20 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0002_lead_project_manager_lead_sales_person"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DealOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("contact_number", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImplementationPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OpportunitySourceMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deal_id", models.CharField(blank=True, max_length=50, unique=True)),
                ("deal_name", models.CharField(max_length=255)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("PROSPECTING", "Prospecting"),
                            ("QUALIFICATION", "Qualification"),
                            ("PROPOSAL", "Proposal"),
                            ("NEGOTIATION", "Negotiation"),
                            ("CLOSED_WON", "Closed Won"),
                            ("CLOSED_LOST", "Closed Lost"),
                        ],
                        default="PROSPECTING",
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "currency",
                    models.CharField(
                        choices=[("INR", "INR"), ("USD", "USD")],
                        default="INR",
                        max_length=10,
                    ),
                ),
                (
                    "deal_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ARR", "Annual Recurring Revenue"),
                            ("FIXED_BID", "Fixed Bid"),
                            ("NEW_LICENSE", "New License"),
                            ("LICENSE_RENEWAL", "License Renewal"),
                            ("T_M", "T&M"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                ("priority", models.CharField(blank=True, default="", max_length=50)),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AMERICAS", "Americas"),
                            ("ANZ", "ANZ"),
                            ("BRAZIL", "Brazil"),
                            ("ROW", "RoW"),
                            ("ISAARC", "ISAARC (India, Nepal...)"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                ("industry", models.CharField(blank=True, default="", max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "customer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "product_name_manual",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Manual fallback or display",
                        max_length=255,
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        blank=True,
                        choices=[("NEW", "New"), ("EXISTING", "Existing")],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "associate_contact",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "inside_salesperson",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "inside_sales_head",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "salesperson_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "sales_head",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "project_manager",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "project_manager_head",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("expected_close_date", models.DateField(blank=True, null=True)),
                ("remark", models.TextField(blank=True, default="")),
                ("won_lost_reason", models.TextField(blank=True, default="")),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deal_owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_deals_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deals",
                        to="leads.lead",
                    ),
                ),
                (
                    "deal_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_deals",
                        to="deals.dealowner",
                    ),
                ),
                (
                    "implementation_partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="deals.implementationpartner",
                    ),
                ),
                (
                    "opportunity_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="deals.opportunitysourcemaster",
                    ),
                ),
                ("products", models.ManyToManyField(blank=True, to="deals.product")),
            ],
        ),
    ]
