# Generated by Django 5.2.4 on 2026-02-11 12:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('customer_type', models.CharField(choices=[('PARTNER', 'Partner'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_person', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('gstin', models.CharField(blank=True, default='', max_length=15, verbose_name='GSTIN')),
                ('pan', models.CharField(blank=True, default='', max_length=10, verbose_name='PAN')),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('state_code', models.CharField(blank=True, default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImplementationPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('AE IND', 'AE IND'), ('AE USA', 'AE USA')], default='AE IND', max_length=10)),
                ('deal_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('deal_name', models.CharField(max_length=255)),
                ('deal_date', models.DateField(default=django.utils.timezone.localdate)),
                ('stage', models.CharField(choices=[('DEAL_CREATED', 'Deal created'), ('COST_SHEET', 'Cost Sheet'), ('ESTIMATES', 'Estimates'), ('SALES_ORDER', 'Sales Order'), ('INVOICE', 'Invoice'), ('PAYMENT', 'Payment')], default='DEAL_CREATED', max_length=50)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EURO', 'EURO')], default='INR', max_length=10)),
                ('fx_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=15)),
                ('deal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deal_type', models.CharField(blank=True, choices=[('LICENSE', 'License'), ('SERVICES', 'Services')], default='', max_length=50)),
                ('priority', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('end_customer', models.CharField(blank=True, default='', max_length=255)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('client_type', models.CharField(blank=True, choices=[('NEW', 'New'), ('EXISTING', 'Existing')], default='', max_length=20)),
                ('inside_salesperson', models.CharField(blank=True, default='', max_length=255)),
                ('inside_sales_head', models.CharField(blank=True, default='', max_length=255)),
                ('salesperson_name', models.CharField(blank=True, default='', max_length=255)),
                ('sales_head', models.CharField(blank=True, default='', max_length=255)),
                ('project_manager', models.CharField(blank=True, default='', max_length=255)),
                ('project_manager_head', models.CharField(blank=True, default='', max_length=255)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, default='')),
                ('won_lost_reason', models.TextField(blank=True, default='')),
                ('hubspot_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='deals.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='DealAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='deal_attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_attachments', to='deals.deal')),
            ],
        ),
        migrations.CreateModel(
            name='DealTypeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LICENSE', 'License'), ('SERVICES', 'Services')], max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_types', to='deals.deal')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('action_type', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted')], default='UPDATE', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='deals_audit_content_81b79c_idx')],
            },
        ),
    ]
