# Generated by Django 5.2.4 on 2026-01-23 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0004_industrymaster_remove_deal_industry"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="deals.industrymaster",
            ),
        ),
    ]
