# Generated by Django 5.2.4 on 2026-02-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0009_countrymaster_remove_deal_deal_owner_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="company",
            field=models.CharField(
                choices=[("AE IND", "AE IND"), ("AE USA", "AE USA")],
                default="AE IND",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="deal_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="deal",
            name="fx_rate",
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="deal",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="deal",
            name="currency",
            field=models.CharField(
                choices=[("INR", "INR"), ("USD", "USD"), ("EURO", "EURO")],
                default="INR",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_type",
            field=models.CharField(
                blank=True,
                choices=[("LICENSE", "License"), ("SERVICES", "Services")],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="probability",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="deal",
            name="product_name_manual",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="deal",
            name="stage",
            field=models.CharField(
                choices=[
                    ("DEAL_CREATED", "Deal created"),
                    ("COST_SHEET", "Cost Sheet"),
                    ("ESTIMATES", "Estimates"),
                    ("SALES_ORDER", "Sales Order"),
                    ("INVOICE", "Invoice"),
                    ("PAYMENT", "Payment"),
                ],
                default="DEAL_CREATED",
                max_length=50,
            ),
        ),
    ]
