# Generated by Django 5.2.4 on 2026-02-02 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0010_deal_company_deal_deal_amount_deal_fx_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="deal_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
