# Generated by Django 5.2.4 on 2026-02-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0011_deal_deal_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="project_name",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=255
            ),
        ),
    ]
