# Generated by Django 5.2.4 on 2026-01-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorder",
            name="so_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
