# Generated by Django 5.2.4 on 2026-01-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_orders", "0002_alter_salesorder_so_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderitem",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
