# Generated by Django 5.2.4 on 2026-01-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_orders", "0003_salesorderitem_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="customer_code",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
