# Generated by Django 5.2.4 on 2026-01-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_orders", "0004_salesorder_customer_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="customer_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
