# Generated by Django 5.2.4 on 2026-01-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimates", "0004_estimate_approval_notes_estimate_approval_status_and_more"),
        ("sales_orders", "0006_salesorderitem_discount_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="estimates",
            field=models.ManyToManyField(
                blank=True, related_name="sales_orders", to="estimates.estimate"
            ),
        ),
    ]
