# Generated by Django 5.2.4 on 2026-02-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0005_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='column_labels',
            field=models.JSONField(blank=True, default=dict, help_text='Custom labels for items table headers'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='subscription_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='subscription_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='hsn_sac',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='HSN/SAC'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='unit',
            field=models.CharField(default='Nos', max_length=20),
        ),
    ]
