# Generated by Django 5.2.4 on 2026-01-27 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estimate",
            name="description_memo",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="estimate",
            name="estimate_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="estimate",
            name="terms_conditions",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="EstimateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sr_no", models.IntegerField()),
                ("particulars", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "qty",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "estimate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="estimates.estimate",
                    ),
                ),
            ],
        ),
    ]
