# Generated by Django 5.2.4 on 2026-01-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimates", "0002_estimate_description_memo_estimate_estimate_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estimate",
            name="estimate_id",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
