# Generated by Django 5.2.4 on 2026-01-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_orders", "0005_salesorder_customer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderitem",
            name="discount_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="salesorderitem",
            name="tax_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
