# Generated by Django 5.2.4 on 2026-02-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0007_salesorder_estimates'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='po_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='po_to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
