# Generated by Django 5.2.4 on 2026-01-05 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0002_lead_project_manager_lead_sales_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=100)),
                ("api_key", models.CharField(blank=True, max_length=255, null=True)),
                ("client_id", models.CharField(blank=True, max_length=255, null=True)),
                ("oauth_credentials", models.TextField(blank=True, null=True)),
                ("token", models.CharField(blank=True, max_length=255, null=True)),
                ("secret_key", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField()),
                ("description", models.TextField()),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "amount_received",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FOR_REVIEW", "For Review"),
                            ("CATEGORIZED", "Categorized"),
                            ("EXCLUDED", "Excluded"),
                        ],
                        default="FOR_REVIEW",
                        max_length=20,
                    ),
                ),
                (
                    "exclusion_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank_connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="finance.bankconnection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_no", models.CharField(max_length=100, unique=True)),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("open_balance", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("PARTIAL", "Partially Paid"),
                            ("PAID", "Paid"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="leads.lead",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_no",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("payment_date", models.DateField()),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("payment_method", models.CharField(max_length=100)),
                (
                    "amount_received",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "tds_receivable",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNRECONCILED", "Unreconciled"),
                            ("RECONCILED", "Reconciled"),
                        ],
                        default="UNRECONCILED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matched_receipts",
                        to="finance.banktransaction",
                    ),
                ),
                (
                    "deposit_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipt_vouchers",
                        to="finance.bankconnection",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="leads.lead",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="receipt_attachments/")),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receipt_voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="finance.receiptvoucher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "tds_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "bank_charges",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="finance.invoice",
                    ),
                ),
                (
                    "receipt_voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="finance.receiptvoucher",
                    ),
                ),
            ],
        ),
    ]
