# Generated by Django 5.2.4 on 2026-01-05 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("leads", "0002_lead_project_manager_lead_sales_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiptvoucher",
            name="customer_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="receiptvoucher",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="leads.lead",
            ),
        ),
    ]
