# Generated by Django 5.2.4 on 2026-01-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_banktransaction_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransaction",
            name="reconciliation_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
