# Generated by Django 5.2.4 on 2026-01-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_banktransaction_reconciliation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransaction",
            name="balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="cheque_ref_no",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Cheque No./Ref. No.",
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="deposit_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="posted_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="transaction_remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="value_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="withdrawal_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
