# Generated by Django 5.2.4 on 2026-02-02 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cost_sheets",
            "0013_costsheet_customer_name_costsheet_project_manager_and_more",
        ),
        ("deals", "0009_countrymaster_remove_deal_deal_owner_user_and_more"),
        ("finance", "0005_banktransaction_balance_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StateMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="GST State Code (e.g., 27 for Maharashtra)",
                        max_length=2,
                        unique=True,
                    ),
                ),
                ("is_union_territory", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "States",
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="approval_comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_invoices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="billing_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="cost_sheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="cost_sheets.costsheet",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="currency",
            field=models.CharField(default="INR", max_length=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="customer_gstin",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="deal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="deals.deal",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="grand_total_words",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("DOMESTIC", "Domestic (CGST/SGST)"),
                    ("INTER_STATE", "Inter-State (IGST)"),
                    ("EXPORT", "Export (Zero Rated)"),
                    ("USA", "USA Invoice (Non-GST)"),
                ],
                default="DOMESTIC",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="place_of_supply",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="round_off",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="shipping_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="invoice",
            name="taxable_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="invoice",
            name="total_discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="invoice",
            name="total_tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("SENT", "Sent to Customer"),
                    ("PARTIAL", "Partially Paid"),
                    ("PAID", "Paid"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sr_no", models.IntegerField()),
                ("description", models.TextField()),
                ("hsn_sac", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=15)),
                ("taxable_value", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "cgst_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "sgst_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "igst_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "igst_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="finance.invoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("registered_address", models.TextField()),
                ("gstin", models.CharField(blank=True, max_length=15, null=True)),
                ("pan", models.CharField(blank=True, max_length=10, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="company/signatures/"
                    ),
                ),
                (
                    "company_seal",
                    models.ImageField(
                        blank=True, null=True, upload_to="company/seals/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.statemaster",
                    ),
                ),
            ],
        ),
    ]
