# Generated by Django 5.2.4 on 2026-02-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_statemaster_invoice_approval_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_gst_applicable",
            field=models.BooleanField(default=True),
        ),
    ]
