# Generated by Django 5.2.4 on 2026-02-02 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estimates", "0005_emaillog"),
        ("finance", "0007_invoice_is_gst_applicable"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="proposal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="estimates.proposal",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sales_tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sales_tax_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
