# Generated by Django 5.2.4 on 2026-02-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_invoice_proposal_invoice_sales_tax_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="authorized_signatory_name",
            field=models.CharField(
                blank=True,
                help_text="Name of authorized signatory",
                max_length=255,
                null=True,
            ),
        ),
    ]
