# Generated by Django 5.2.4 on 2026-01-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="hubspot_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="probability",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Probability in percentage (0-100)",
                max_digits=5,
            ),
        ),
    ]
