# Generated by Django 5.2.4 on 2026-01-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0002_deal_hubspot_id_deal_last_synced_at_deal_probability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="probability",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Probability in percentage (0-100)",
                max_digits=10,
            ),
        ),
    ]
