# Generated by Django 5.2.4 on 2026-01-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0007_deal_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="customer_name",
        ),
    ]
