# Generated by Django 5.2.4 on 2026-02-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0012_alter_deal_project_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="country",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="deal_owner",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="opportunity_source",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="associate_contact",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="probability",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="product_name_manual",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="products",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="project_name",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="region",
        ),
        migrations.DeleteModel(
            name="CountryMaster",
        ),
        migrations.DeleteModel(
            name="DealOwner",
        ),
        migrations.DeleteModel(
            name="IndustryMaster",
        ),
        migrations.DeleteModel(
            name="OpportunitySourceMaster",
        ),
    ]
