# Generated by Django 5.2.4 on 2026-02-11 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_sheet_no', models.CharField(blank=True, max_length=100, unique=True)),
                ('cost_sheet_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Draft'), ('SUBMITTED', 'Pending for Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVERTED', 'Reverted')], default='PENDING', max_length=20)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('project_name', models.CharField(blank=True, default='', max_length=255)),
                ('project_manager', models.CharField(blank=True, default='', max_length=255)),
                ('sales_person', models.CharField(blank=True, default='', max_length=255)),
                ('approval_comments', models.TextField(blank=True, null=True)),
                ('revert_comments', models.TextField(blank=True, null=True)),
                ('license_remarks', models.TextField(blank=True, default='')),
                ('implementation_remarks', models.TextField(blank=True, default='')),
                ('support_remarks', models.TextField(blank=True, default='')),
                ('infra_remarks', models.TextField(blank=True, default='')),
                ('other_remarks', models.TextField(blank=True, default='')),
                ('overall_remarks', models.TextField(blank=True, default='')),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_estimated_margin', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_estimated_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostSheetAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cost_sheet_attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfrastructureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('qty', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('months', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('rate_per_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('remark', models.TextField(blank=True, default='')),
                ('margin_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('estimated_margin_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.CharField(blank=True, default='', max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('qty', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('period', models.CharField(blank=True, default='', max_length=100)),
                ('remark', models.TextField(blank=True, default='')),
                ('margin_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('estimated_margin_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='OtherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('remark', models.TextField(blank=True, default='')),
                ('margin_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('estimated_margin_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImplementationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('num_resources', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('num_days', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('rate_per_day', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('remark', models.TextField(blank=True, default='')),
                ('margin_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_days', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('estimated_margin_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSupportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('num_resources', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('num_days', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('rate_per_day', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('remark', models.TextField(blank=True, default='')),
                ('margin_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_days', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('estimated_margin_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
    ]
