# Generated by Django 5.2.4 on 2025-12-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost_sheets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="costsheet",
            name="cost_sheet_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
