# Generated by Django 5.2.4 on 2025-12-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost_sheets", "0002_costsheet_cost_sheet_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costsheet",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Draft"),
                    ("SUBMITTED", "Pending for Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
