# Generated by Django 5.2.4 on 2026-01-02 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost_sheets", "0005_costsheetattachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "margin_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "estimated_margin_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "estimated_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "cost_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_items",
                        to="cost_sheets.costsheet",
                    ),
                ),
            ],
        ),
    ]
