# Generated by Django 5.2.4 on 2026-01-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost_sheets", "0006_otheritem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costsheet",
            name="cost_sheet_no",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
