# Generated by Django 5.2.4 on 2026-01-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost_sheets", "0008_costsheet_implementation_remarks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructureitem",
            name="remark",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="licenseitem",
            name="remark",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="otheritem",
            name="remark",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="serviceimplementationitem",
            name="remark",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="servicesupportitem",
            name="remark",
            field=models.TextField(blank=True, default=""),
        ),
    ]
