# Generated by Django 5.2.4 on 2026-01-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost_sheets", "0009_infrastructureitem_remark_licenseitem_remark_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="costsheet",
            name="revert_comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="costsheet",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Draft"),
                    ("SUBMITTED", "Pending for Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("REVERTED", "Reverted"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
