# Generated by Django 5.2.4 on 2026-01-23 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost_sheets", "0011_costsheet_deal"),
        ("leads", "0002_lead_project_manager_lead_sales_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costsheet",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_sheets",
                to="leads.lead",
            ),
        ),
    ]
