# Generated by Django 5.2.4 on 2026-02-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_invoice_authorized_signatory_invoice_company_seal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="cin",
            field=models.CharField(
                blank=True, max_length=21, null=True, verbose_name="CIN"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="msme_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="MSME Number"
            ),
        ),
    ]
