# Generated by Django 5.2.4 on 2026-02-11 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_companyprofile_cin_companyprofile_msme_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="address_line_1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="address_line_2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="alias_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="base_currency",
            field=models.CharField(default="INR", max_length=10),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="country",
            field=models.CharField(default="India", max_length=100),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="currency_symbol",
            field=models.CharField(default="₹ / INR", max_length=10),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="decimal_places",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="financial_year_begins",
            field=models.CharField(default="01-Apr", max_length=20),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="is_gst_applicable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="company/logos/"),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="msme_registered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="pincode",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="state_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="tan",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="registered_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finance.statemaster",
            ),
        ),
    ]
