# Generated by Django 5.2.4 on 2026-02-05 11:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0014_remove_deal_implementation_partner_customer_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="deal_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.CreateModel(
            name="DealAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="deal_attachments/")),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deal_attachments",
                        to="deals.deal",
                    ),
                ),
            ],
        ),
    ]
