# Generated by Django 5.2.4 on 2026-02-06 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("deals", "0015_alter_deal_deal_date_dealattachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audittrail",
            name="deal",
        ),
        migrations.AddField(
            model_name="audittrail",
            name="content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="audittrail",
            name="object_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name="audittrail",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="deals_audit_content_81b79c_idx",
            ),
        ),
    ]
