# Generated by Django 5.2.4 on 2026-02-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0016_remove_audittrail_deal_audittrail_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="gstin",
            field=models.CharField(
                blank=True, default="", max_length=15, verbose_name="GSTIN"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="pan",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="PAN"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="state",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="state_code",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
