# Generated by Django 5.2.4 on 2025-12-30 09:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost_sheet_no", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending for Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "total_estimated_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "total_estimated_margin",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "total_estimated_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_sheets",
                        to="leads.lead",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InfrastructureItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "qty",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "months",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "rate_per_month",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "margin_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "estimated_margin_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "estimated_price",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "cost_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="infra_items",
                        to="cost_sheets.costsheet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LicenseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=100)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "qty",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("period", models.CharField(max_length=100)),
                (
                    "margin_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "estimated_margin_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "estimated_price",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "cost_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license_items",
                        to="cost_sheets.costsheet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceImplementationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                (
                    "num_resources",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "num_days",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("rate_per_day", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "margin_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("total_days", models.IntegerField()),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "estimated_margin_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "estimated_price",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "cost_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="implementation_items",
                        to="cost_sheets.costsheet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceSupportItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                (
                    "num_resources",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "num_days",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("rate_per_day", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "margin_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("total_days", models.IntegerField()),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "estimated_margin_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "estimated_price",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "cost_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_items",
                        to="cost_sheets.costsheet",
                    ),
                ),
            ],
        ),
    ]
