# Generated by Django 5.2.4 on 2026-01-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost_sheets", "0007_alter_costsheet_cost_sheet_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="costsheet",
            name="implementation_remarks",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="costsheet",
            name="infra_remarks",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="costsheet",
            name="license_remarks",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="costsheet",
            name="other_remarks",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="costsheet",
            name="overall_remarks",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="costsheet",
            name="support_remarks",
            field=models.TextField(blank=True, default=""),
        ),
    ]
