# Generated by Django 5.2.4 on 2026-01-23 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost_sheets", "0010_costsheet_revert_comments_alter_costsheet_status"),
        ("deals", "0005_deal_industry"),
    ]

    operations = [
        migrations.AddField(
            model_name="costsheet",
            name="deal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cost_sheets",
                to="deals.deal",
            ),
        ),
    ]
