# Generated by Django 5.2.4 on 2026-01-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost_sheets", "0012_alter_costsheet_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="costsheet",
            name="customer_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="costsheet",
            name="project_manager",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="costsheet",
            name="project_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="costsheet",
            name="sales_person",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
