# Generated by Django 5.2.4 on 2026-01-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="project_manager",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="lead",
            name="sales_person",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
