# Generated by Django 5.2.4 on 2026-02-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_lead_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="company",
            field=models.CharField(
                choices=[("AE IND", "AE IND"), ("AE USA", "AE USA")],
                default="AE IND",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="lead_no",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
