# Generated by Django 5.2.4 on 2026-02-02 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_lead_company_alter_lead_lead_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="lead_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
