# Generated by Django 5.2.4 on 2026-01-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_receiptvoucher_customer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransaction",
            name="source",
            field=models.CharField(
                choices=[("AUTO", "Auto Download"), ("MANUAL", "Manual Upload")],
                default="AUTO",
                max_length=10,
            ),
        ),
    ]
