# Generated by Django 5.2.4 on 2026-02-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_add_authorized_signatory"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="authorized_signatory",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="company_seal",
            field=models.ImageField(blank=True, null=True, upload_to="invoices/seals/"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="gst_declaration",
            field=models.TextField(
                blank=True,
                default="We declare that this invoice shows the actual price of the goods described and that all particulars are true and correct. This invoice is issued under Rule 46 of the CGST Rules, 2017.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="lut_declaration",
            field=models.TextField(
                blank=True,
                default="Supply meant for export under Letter of Undertaking (LUT) without payment of Integrated Tax as per Section 16(3) of the IGST Act, 2017 and Rule 96A of the CGST Rules, 2017.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="signature_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="invoices/signatures/"
            ),
        ),
    ]
